@startuml


!theme plain
top to bottom direction

abstract Menu {
  - omListe: ArrayList<OptionMenu>
  - codeQuitter: String
  + ajouterOption(OptionMenu): void
  + afficherMenu(): void
  + supprimerOption(OptionMenu): void
  + executer(AgenceBancaire): void
  + choisir(AgenceBancaire): void
  + modifierOption(int, OptionMenu): void
  + supprimerOption(int): void
}
class MenuGestionComptes
class MenuOperationsComptes
class MenuPrincipal
abstract Option {
  + executer(AgenceBancaire): void
}
class OptionAjouterCompte {
  + executer(AgenceBancaire): void
}
class OptionDeposer {
  + executer(AgenceBancaire): void
  + deposerSurUnCompte(AgenceBancaire, String, double): void
}
class OptionListeDesComptes {
  + executer(AgenceBancaire): void
}
abstract OptionMenu {
  - code: String
  - titre: String
  + afficher(): void
  + executer(AgenceBancaire): void
  + getTitre(): String
  + getCode(): String
}
class OptionRetirer {
  + executer(AgenceBancaire): void
  + retirerSurUnCompte(AgenceBancaire, String, double): void
}
class OptionSupprimerCompte {
  + executer(AgenceBancaire): void
}
class OptionVoirCompte {
  + executer(AgenceBancaire): void
}
class menuTestApp {
  + main(String[]): void
}

OptionMenu ^-[#000082,plain]- Menu
OptionMenu ^-[#000082,plain]- Option
Menu ^-[#2C8C1E,plain]- MenuPrincipal
Menu ^-[#2C8C1E,plain]- MenuGestionComptes
Menu ^-[#2C8C1E,plain]- MenuOperationsComptes
Option ^-[#2C8C1E,plain]- OptionAjouterCompte
Option ^-[#2C8C1E,plain]- OptionDeposer
Option ^-[#2C8C1E,plain]- OptionListeDesComptes
Option ^-[#2C8C1E,plain]- OptionRetirer
Option ^-[#2C8C1E,plain]- OptionSupprimerCompte
Option ^-[#2C8C1E,plain]- OptionVoirCompte

OptionMenu "0..*" <--* "1" Menu

menuTestApp -[#000000,dashed]-> OptionMenu
menuTestApp -[#000000,dashed]-> Menu
menuTestApp -[#000000,dashed]-> Option


@enduml